name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: lnbits/lnbits/.github/workflows/lint.yml@dev

  payments:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: make test-payments test-server
